force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <description>This is custom object which is connected with Hotel__c with Lookup Relationship. Where one Hotel has multiple Reviews and This Object contains appropriate Fields of the Review. This object is used to store the record of the review.</description>
    <label>Review</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Cleanliness_And_Hygiene__c.field-meta.xml
<CustomField>
    <fullName>Cleanliness_And_Hygiene__c</fullName>
    <description>This field stores the rating of Cleanliness and hygiene.</description>
    <label>Cleanliness And Hygiene</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This Field store the message of the user</description>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Food_Quality__c.field-meta.xml
<CustomField>
    <fullName>Food_Quality__c</fullName>
    <description>This Field stores the rating of food quality.</description>
    <label>Food Quality</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Hospitality__c.field-meta.xml
<CustomField>
    <fullName>Hospitality__c</fullName>
    <description>This field contains the rating of Hospitality of Hotel.</description>
    <label>Hospitality</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Review_Title__c.field-meta.xml
<CustomField>
    <fullName>Review_Title__c</fullName>
    <description>This field stores the particular review title</description>
    <label>Review Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Value_For_Money__c.field-meta.xml
<CustomField>
    <fullName>Value_For_Money__c</fullName>
    <description>This field will store the rating of value for money.</description>
    <label>Value For Money</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ReviewController.cls
public with sharing class ReviewController {
    
    @AuraEnabled
    public static void addReview(String reviewDetails){
       
        Map<String, String> jsonMap = (Map<String, String>) JSON.deserializeUntyped(reviewDetails);

        Integer valueForMoney = Integer.valueOf(jsonMap.get('ValueForMoney'));
        Integer foodQuality = Integer.valueOf(jsonMap.get('FoodQuality'));
        Integer hospitality = Integer.valueOf(jsonMap.get('Hospitality'));
        Integer cleanlinessAndHygiene = Integer.valueOf(jsonMap.get('CleanlinessAndHygiene'));
        String reviewHeading = (String)jsonMap.get('ReviewHeading');
        String reviewDescription = (String)jsonMap.get('ReviewDescription');

        Review__c  review = new Review__c(Value_For_Money__c = valueForMoney,Food_Quality__c = foodQuality,Hospitality__c=hospitality,Cleanliness_And_Hygiene__c=cleanlinessAndHygiene ,Description__c =reviewDescription,Review_Title__c = reviewHeading);

        try {
            insert review;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}