force-app/main/default/objects/Error_Logger__c/Error_Logger__c.object-meta.xml
<CustomObject>
    <description>This object will used to create error record of DML operation.(This will used in Flows and Triggers.)</description>
    <label>Error Logger</label>
    <nameField>
        <label>Error Logger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Logger__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Error Message is stored in this field.</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <description>Object Name on which DML operation is happened

.</description>
    <label>Source Object</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Source_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Record_Id__c</fullName>
    <description>Record id of that object on which error occurred.</description>
    <label>Source Record Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RESErrorLogger.cls
/*
*********************************************************
Apex Class Name    : RESErrorLoggerTest
Created Date       : March 24, 2025
@description       : This class is used for creating a error log throughout the org.
@author            : Pritkumar Prajapati
@date			   : March 24, 2025
@JIRA			   : GT25-61
Revision Log:
Ver   Date         Author                               Modification
1.0   24-03-2025   Pritkumar Prajapati                 Initial Version
*********************************************************
*/

public without sharing class RESErrorLogger {
/*
    *********************************************************
    @Method Name    : createErrorLog
    @author         : Pritkumar Prajapati
    @description    : This method is used to create the error log for the DML operations
    @param          : String name, String message, String objectName, String objectRecordId
    @return         : void
	@date			: March 24, 2025
	@JIRA			: GT25-62
    ********************************************************
*/
    public static void createErrorLog(String name, String message, String objectName, String objectRecordId){
        Error_Logger__c errLog = new Error_Logger__c();
        errLog.Name = name;
        errLog.Message__c = message;
        errLog.Source_Object__c = objectName;
        errLog.Source_Record_Id__c = objectRecordId;

        try {
            insert errLog;
        } catch (DmlException e) {
            throw e;
        }
    }
}