force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>Hotel object is the custom object used to store the information about each hotel including different custom fields about that particular hotel.</description>
    <label>Hotel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Avg_Cleanliness_And_Hygiene__c.field-meta.xml
<CustomField>
    <fullName>Avg_Cleanliness_And_Hygiene__c</fullName>
    <description>This is the formula to calculate avg rating for Cleanliness and hygiene</description>
    <formula>IF( Total_Reviews__c &lt;&gt; 0, Total_Cleanliness_And_Hygiene__c  / Total_Reviews__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Avg Cleanliness And Hygiene</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Avg_Food_Quality__c.field-meta.xml
<CustomField>
    <fullName>Avg_Food_Quality__c</fullName>
    <description>This is the formula to calculate avg rating for Food quality</description>
    <formula>IF( Total_Reviews__c &lt;&gt; 0, Total_Food_Quality__c  / Total_Reviews__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Avg Food Quality</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Avg_Hospitality__c.field-meta.xml
<CustomField>
    <fullName>Avg_Hospitality__c</fullName>
    <description>This is the formula to calculate avg rating for Hospitality</description>
    <formula>IF( Total_Reviews__c &lt;&gt; 0, Total_Hospitality__c  / Total_Reviews__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Avg Hospitality</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Avg_Value_For_Money__c.field-meta.xml
<CustomField>
    <fullName>Avg_Value_For_Money__c</fullName>
    <description>This is the formula to calculate avg rating for value for money</description>
    <formula>IF( Total_Reviews__c &lt;&gt; 0, Total_Value_For_Money__c  / Total_Reviews__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Avg Value For Money</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Banner_Photo_Url__c.field-meta.xml
<CustomField>
    <fullName>Banner_Photo_Url__c</fullName>
    <description>Banner Photo Url is the custome field used to store the Url of the Banner Image.</description>
    <label>Banner Photo Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>This Field will show the city of the Hotel</description>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description is the custom field that is used to store the description of the Hotel.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Front_Img__c.field-meta.xml
<CustomField>
    <fullName>Front_Img__c</fullName>
    <label>Front Img</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Includes__c.field-meta.xml
<CustomField>
    <fullName>Includes__c</fullName>
    <label>Includes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Facilities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Not_Includes__c.field-meta.xml
<CustomField>
    <fullName>Not_Includes__c</fullName>
    <label>Not Includes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Facilities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Overall_Rating__c.field-meta.xml
<CustomField>
    <fullName>Overall_Rating__c</fullName>
    <description>This field stores the overall Average rating of a particular hotel</description>
    <formula>IF( Total_Reviews__c &lt;&gt; 0,( Avg_Cleanliness_And_Hygiene__c + Avg_Food_Quality__c + Avg_Value_For_Money__c + Avg_Hospitality__c ) / 4 , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Overall Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Peripheral_Img__c.field-meta.xml
<CustomField>
    <fullName>Peripheral_Img__c</fullName>
    <label>Peripheral Img</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Safety_Rules__c.field-meta.xml
<CustomField>
    <fullName>Safety_Rules__c</fullName>
    <label>Safety Rules</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Covid Test Kit</fullName>
            </value>
            <value>
                <fullName>Hand Sanitizers</fullName>
            </value>
            <value>
                <fullName>Social Distancing</fullName>
            </value>
            <value>
                <fullName>Limited Visitors</fullName>
            </value>
            <value>
                <fullName>Safety Kit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>This Field Indicate the State of the Hotel</description>
    <label>State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Total_Reviews__c.field-meta.xml
<CustomField>
    <fullName>Total_Reviews__c</fullName>
    <description>This Field Indicates total Number of reviews.</description>
    <label>Total Reviews</label>
    <summaryForeignKey>Review__c.Hotel__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Unique_Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Hotel_Name__c</fullName>
    <description>Stores the name of the hotel in kebab case format to uniquely distinguish them</description>
    <label>Unique Hotel Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <description>This is custom object which is connected with Hotel__c with Lookup Relationship. Where one Hotel has multiple Reviews and This Object contains appropriate Fields of the Review. This object is used to store the record of the review.</description>
    <label>Review</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Avg_Rating__c.field-meta.xml
<CustomField>
    <fullName>Avg_Rating__c</fullName>
    <description>This field stores the Average rating of perticular review</description>
    <formula>( Cleanliness_And_Hygiene__c +  Food_Quality__c  +  Hospitality__c +  Value_For_Money__c ) / 4</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Avg Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This Field store the message of the user</description>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <description>This Field Relate the Review object to Hotel Object which is many to one relationship from the review</description>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Review_Title__c.field-meta.xml
<CustomField>
    <fullName>Review_Title__c</fullName>
    <description>This field stores the particular review title</description>
    <label>Review Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Reviewer_Name__c.field-meta.xml
<CustomField>
    <fullName>Reviewer_Name__c</fullName>
    <description>This field stores the name of the reviewer</description>
    <formula>Account__r.LastName</formula>
    <label>Reviewer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Facilities.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Food Order</fullName>
    </customValue>
    <customValue>
        <fullName>Non-veg. Food</fullName>
    </customValue>
    <customValue>
        <fullName>Pets</fullName>
    </customValue>
    <customValue>
        <fullName>Parking space</fullName>
    </customValue>
    <customValue>
        <fullName>Room Service</fullName>
    </customValue>
    <customValue>
        <fullName>Telephone</fullName>
    </customValue>
    <customValue>
        <fullName>Free Breakfast</fullName>
    </customValue>
    <customValue>
        <fullName>A.C.</fullName>
    </customValue>
    <customValue>
        <fullName>Television</fullName>
    </customValue>
    <customValue>
        <fullName>Veg. Food</fullName>
        <isActive>false</isActive>
        <label>Veg. Food</label>
    </customValue>
    <masterLabel>Facilities</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HotelWrapper.cls
public without sharing class HotelWrapper {
    @AuraEnabled(cacheable=true)
    public static List<HotelWrapperData> getHotelWithRating(String hotelName){
        try {
            List<HotelWrapperData> hotelWrapList = new List<HotelWrapperData>();
            Hotel__c hotelList = [SELECT Id, Name, Banner_Photo_Url__c, Front_Img__c,Location__c, Includes__c, Not_Includes__c, Peripheral_Img__c, Safety_Rules__c,  Total_Reviews__c, Avg_Value_For_Money__c, Avg_Hospitality__c, Avg_Food_Quality__c, Avg_Cleanliness_And_Hygiene__c, Overall_Rating__c, City__c, State__c, Description__c, Unique_Hotel_Name__c, (SELECT Id, Avg_Rating__c, Reviewer_Name__c, CreatedDate, Review_Title__c, Description__c FROM Reviews__r) FROM Hotel__c WHERE Unique_Hotel_Name__c = :hotelName];

            hotelWrapList.add(new HotelWrapperData(hotelList, hotelList.Reviews__r));
            return hotelWrapList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class HotelWrapperData{
        @AuraEnabled public Hotel__c hotelRecord{get;set;}
        @AuraEnabled public List<Review__c> ratingList{get;set;}
        public HotelWrapperData(Hotel__c hotelRecord, List<Review__c> ratingList){
            this.hotelRecord = hotelRecord;
            this.ratingList = ratingList;
        }
    }
}