force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>Hotel object is the custom object used to store the information about each hotel including different custom fields about that particular hotel.</description>
    <label>Hotel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Address is a custom field in the Hotel object that is used to store the address of the hotel.</description>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email is the custom field that is used to store the Email of the Hotel.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone is the custom field that is used to store the Phone of the Hotel.</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Order/fields/Checkin__c.field-meta.xml
<CustomField>
    <fullName>Checkin__c</fullName>
    <description>This will store the information of booking checkin date</description>
    <label>Checkin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Checkout__c.field-meta.xml
<CustomField>
    <fullName>Checkout__c</fullName>
    <description>This will store the checkout date of booking</description>
    <label>Checkout</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Guest_Email__c.field-meta.xml
<CustomField>
    <fullName>Guest_Email__c</fullName>
    <description>This field will store the email of the guest who is staying</description>
    <label>Guest Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Order/fields/Guest_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_First_Name__c</fullName>
    <description>This field will store the first name of the guest who is staying</description>
    <label>Guest First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Guest_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Guest_Last_Name__c</fullName>
    <description>This field will store the last name of the guest who is staying</description>
    <label>Guest Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Guest_Phone__c.field-meta.xml
<CustomField>
    <fullName>Guest_Phone__c</fullName>
    <description>This field will store the Phone of the guest who is staying</description>
    <label>Guest Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hotel is the lookup to Hotel Object, which describes the hotel product is related to which Hotel.</description>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Hotel Products</relationshipLabel>
    <relationshipName>Hotel_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RES_GenerateInvoicePDFAction.cls
public without sharing class RES_GenerateInvoicePDFAction {

    public class Input {
        @InvocableVariable(label='Order ID' required=true)
        public Id orderId;
    }

    public class Output {
        @InvocableVariable(label='ContentVersion ID')
        public Id contentVersionId;
    }

    @InvocableMethod(label='Generate Invoice PDF and Create Attachment' description='Generates a PDF invoice for a given Order ID and creates a ContentVersion.')
    public static List<Output> generateInvoiceAndCreateAttachment(List<Input> inputs) {
        List<Output> outputs = new List<Output>();
        Output output = new Output();

        if (!inputs.isEmpty() && inputs[0].orderId != null) {
            Id orderId = inputs[0].orderId;
            try {
                Order orderRecord = [SELECT Id, OrderNumber, AccountId, Status, TotalAmount, CreatedDate, Guest_First_Name__c, Guest_Last_Name__c,Guest_Email__c,Guest_Phone__c, (SELECT Id, OrderId ,Product2Id ,Product2.Image_URL__c, Product2.Hotel__r.Name,Product2.Hotel__r.Address__c ,Product2.Hotel__r.Email__c ,Product2.Hotel__r.Phone__c , Product2.Name , Quantity , UnitPrice, TotalPrice, checkin__c , checkout__c FROM OrderItems) FROM Order WHERE Id =: orderId LIMIT 1];

                System.debug('Order ID being passed to VF page: ' + orderRecord.Id);
            System.debug('Account ID being passed to VF page: ' + orderRecord.AccountId);

                if (orderRecord != null) {
                    PageReference pdfPage = Page.resHotelInvoicePDF;
                    pdfPage.getParameters().put('id', orderRecord.Id);
                    pdfPage.getParameters().put('accId', orderRecord.AccountId);

                    Blob pdfBlob = pdfPage.getContentAsPDF();
                    String attachmentName = 'Invoice_' + orderRecord.OrderNumber + '.pdf';

                    ContentVersion cv = new ContentVersion();
                    cv.Title = attachmentName.removeEnd('.pdf');
                    cv.PathOnClient = attachmentName;
                    cv.VersionData = pdfBlob;
                    cv.Origin = 'C';
                    insert cv;
                    ContentDocumentLink cdl = new ContentDocumentLink();
                    cdl.ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
                    cdl.LinkedEntityId = orderRecord.Id;
                    cdl.ShareType = 'V';
                    insert cdl;

                    output.contentVersionId = cv.Id;

                } else {
                    output.contentVersionId = null;
                }

            } catch (Exception e) {
                output.contentVersionId = null;
            }
        } else {
            output.contentVersionId = null;
        }

        outputs.add(output);
        return outputs;
    }
}