force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>Hotel object is the custom object used to store the information about each hotel including different custom fields about that particular hotel.</description>
    <label>Hotel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>This Field will show the city of the Hotel</description>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Featured__c.field-meta.xml
<CustomField>
    <fullName>Featured__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This Field is Accessible for Admin Only and This will help to sort the hotels on the basis of the Checkbox.</description>
    <label>Featured</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Unique_Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Hotel_Name__c</fullName>
    <description>Stores the name of the hotel in kebab case format to uniquely distinguish them</description>
    <label>Unique Hotel Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <description>This is custom object which is connected with Hotel__c with Lookup Relationship. Where one Hotel has multiple Reviews and This Object contains appropriate Fields of the Review. This object is used to store the record of the review.</description>
    <label>Review</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>This is the master-detail field between Review and Account object</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Cleanliness_And_Hygiene__c.field-meta.xml
<CustomField>
    <fullName>Cleanliness_And_Hygiene__c</fullName>
    <description>This field stores the rating of Cleanliness and hygiene.</description>
    <label>Cleanliness And Hygiene</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Food_Quality__c.field-meta.xml
<CustomField>
    <fullName>Food_Quality__c</fullName>
    <description>This Field stores the rating of food quality.</description>
    <label>Food Quality</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Hospitality__c.field-meta.xml
<CustomField>
    <fullName>Hospitality__c</fullName>
    <description>This field contains the rating of Hospitality of Hotel.</description>
    <label>Hospitality</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <description>This Field Relate the Review object to Hotel Object which is many to one relationship from the review</description>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Value_For_Money__c.field-meta.xml
<CustomField>
    <fullName>Value_For_Money__c</fullName>
    <description>This field will store the rating of value for money.</description>
    <label>Value For Money</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RES_Utility_Test.cls
/*
*********************************************************
Apex Class Name    : RES_Utility_Test
Created Date       : March 28, 2025
@description       : This Test Class For RES_Utility 
@author            : Jay patel
@date			   : March 28, 2025
@JIRA			   : GT25-32
Modification Log:
Ver   Date         Author                               Modification
1.0   28-03-2025   Jay Patel                           Initial Version
2.0   01-04-2025   Pritkumar Prajapati                 Added testHotelWithRating method
3.0   02-04-2025   Pritkumar Prajapati                 Added testGetRelatedHotels method
*********************************************************
*/
@isTest
public class RES_Utility_Test {
     /*
    *********************************************************
    @Method Name    : testFeature
    @author         : Jay Patel
    @description    : method to is used for creating record of hotels with enabled featured checkbox
    @param          : void
    @return         : Void
	@date			: March 28, 2025
	@JIRA			: GT25-32
    ********************************************************
	*/
	@isTest
    public static void testFeature(){
        List<Hotel__c> testresultList1 = new List<Hotel__c>();
        for(Integer i = 0;i < 4;i++){
            Hotel__c h1 = new Hotel__c();
            h1.Name = 'H'+i;
            h1.Featured__c = true;
            testresultList1.add(h1);
        }
       
		insert testresultList1;        
        Test.StartTest();
        List<Hotel__c> hotelList1 = RES_Utility.getFeatureHotelCards();
        Test.StopTest();
        
        System.assertEquals(testresultList1.size(),hotelList1.size());
		        
    }
    
     /*
    *********************************************************
    @Method Name    : testFeature
    @author         : Jay Patel
    @description    : method to is used for creating record of hotels.
    @param          : void
    @return         : Void
	@date			: March 28, 2025
	@JIRA			: GT25-32
    ********************************************************
	*/
    @isTest
    public static void testRating(){
        List<Hotel__c> testresultList2 = new List<Hotel__c>();
        for(Integer i = 0;i < 4;i++){
            Hotel__c h1 = new Hotel__c();
            h1.Name = 'H'+i;
            testresultList2.add(h1);
        }
       
		insert testresultList2;        
        Test.StartTest();
        List<Hotel__c> hotelList2 = RES_Utility.getRatingHotelCards();
        Test.StopTest();
        
        System.assertEquals(testresultList2.size(),hotelList2.size());
		        
    }

    /*
    *********************************************************
    @Method Name    : testWrapperData
    @author         : Pritkumar Prajapati
    @description    : method is used to test the functionality of method getHotelWithRating
    @param          : void
    @return         : Void
	@date			: April 1, 2025
	@JIRA			: GT25-26
    ********************************************************
	*/

    @isTest
    private static void testHotelWithRating(){
        Hotel__c testHotel = new Hotel__c(
            Name = 'TestHotel',
            Unique_Hotel_Name__c = 'TestHotelUnique'
        );
        insert testHotel;

        Account acc = new Account(
            LastName = 'TestAcc'
        );
        insert acc;

        List<Review__c> reviewList = new List<Review__c>();
        for(Integer i = 0; i < 3; i++){
            Review__c testReview = new Review__c();
            testReview.Hotel__c = testHotel.Id;
            testReview.Account__c = acc.Id;
            testReview.Cleanliness_And_Hygiene__c = 5;
            testReview.Food_Quality__c = 5;
            testReview.Hospitality__c = 5;
            testReview.Value_For_Money__c = 5;
            reviewList.add(testReview);
        }

        if(!reviewList.isEmpty()){
            insert reviewList;
        }

        Test.startTest();
        List<RES_Utility.HotelWrapperData> result = RES_Utility.getHotelWithRating('TestHotelUnique');
        Test.stopTest();

        System.assertEquals(3, result[0].ratingList.size());
    }

    /*
    *********************************************************
    @Method Name    : testGetRelatedHotels
    @author         : Pritkumar Prajapati
    @description    : method is used to test the functionality of method getRelatedHotels
    @param          : void
    @return         : Void
	@date			: April 2, 2025
	@JIRA			: GT25-31
    ********************************************************
	*/

    @isTest
    private static void testGetRelatedHotels(){
        List<Hotel__c> testresultList = new List<Hotel__c>();
        for(Integer i = 0;i < 4;i++){
            Hotel__c h1 = new Hotel__c();
            h1.Name = 'H'+i;
            h1.City__c = 'testCity';
            testresultList.add(h1);
        }
        if(!testresultList.isEmpty()){
            insert testresultList;
        }

        test.StartTest();
        List<Hotel__c> relatedHotels = RES_Utility.getRelatedHotels('H1','testCity');
        test.StopTest();

        System.assertEquals(3, relatedHotels.size());
    }
}