force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>Hotel object is the custom object used to store the information about each hotel including different custom fields about that particular hotel.</description>
    <label>Hotel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Banner_Photo_Url__c.field-meta.xml
<CustomField>
    <fullName>Banner_Photo_Url__c</fullName>
    <description>Banner Photo Url is the custome field used to store the Url of the Banner Image.</description>
    <label>Banner Photo Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>This Field will show the city of the Hotel</description>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Featured__c.field-meta.xml
<CustomField>
    <fullName>Featured__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This Field is Accessible for Admin Only and This will help to sort the hotels on the basis of the Checkbox.</description>
    <label>Featured</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Overall_Rating__c.field-meta.xml
<CustomField>
    <fullName>Overall_Rating__c</fullName>
    <description>This field stores the overall Average rating of a particular hotel</description>
    <formula>IF( Total_Reviews__c &lt;&gt; 0,( Avg_Cleanliness_And_Hygiene__c + Avg_Food_Quality__c + Avg_Value_For_Money__c + Avg_Hospitality__c ) / 4 , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Overall Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>This Field Indicates the minimum price of the rooms. and the value of room will fill from the flow. Flow will execute when the record of the room is created.</description>
    <label>Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <description>This Field Indicates Average Rating of One Hotel</description>
    <formula>IF( Total_Reviews__c  &lt;&gt; 0,(  Avg_Cleanliness_And_Hygiene__c  +  Avg_Food_Quality__c +  Avg_Value_For_Money__c  +  Avg_Hospitality__c )  /  4 , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>This Field Indicate the State of the Hotel</description>
    <label>State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Unique_Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Hotel_Name__c</fullName>
    <description>Stores the name of the hotel in kebab case format to uniquely distinguish them</description>
    <label>Unique Hotel Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RES_Utility.cls
/*
*********************************************************
Apex Class Name    : RES_Utility
Created Date       : March 28, 2025
@description       : This class is used for Fetching the Hotel Details on Specific Criteria
@author            : Jay patel
@date			   : March 28, 2025
@JIRA			   : GT25-32
Modification Log:
Ver   Date         Author                               Modification
1.0   28-03-2025   Jay Patel                           Initial Version
*********************************************************
*/
public with sharing class RES_Utility {

    /*
    *********************************************************
    @Method Name    : getFeatureHotelCards
    @author         : Jay Patel
    @description    : method to is used for Fetching that hotel whose featured checkbox is checked
    @param          : void
    @return         : List<Hotel__c>
	@date			: March 28, 2025
	@JIRA			: GT25-32
    ********************************************************
	*/
    @AuraEnabled
    public static List<Hotel__c> getFeatureHotelCards() {

        List<Hotel__c> hoteldetails = [SELECT Id,Name,City__c,State__c,Banner_Photo_Url__c,Price__c,Overall_Rating__c,Unique_Hotel_Name__c FROM Hotel__c Where Featured__c = true ORDER BY Rating__c DESC LIMIT 4];

        return hoteldetails;
    }

     /*
    *********************************************************
    @Method Name    : getRatingHotelCards
    @author         : Jay Patel
    @description    : method to is used for Fetching hotels of top rating
    @param          : void
    @return         : List<Hotel__c>
	@date			: March 28, 2025
	@JIRA			: GT25-32
    ********************************************************
	*/
    @AuraEnabled
    public static List<Hotel__c> getRatingHotelCards() {

        List<Hotel__c> hoteldetails = [SELECT Id,Name,City__c,State__c,Banner_Photo_Url__c,Price__c,Overall_Rating__c,Unique_Hotel_Name__c FROM Hotel__c ORDER BY Rating__c DESC LIMIT 4];

        return hoteldetails;
    }
}