force-app/main/default/objects/Booked_Date__c/Booked_Date__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the booked dates for all the individual rooms.</description>
    <label>Booked Date</label>
    <nameField>
        <displayFormat>BD-{00000}</displayFormat>
        <label>Booked Dates</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booked Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booked_Date__c/fields/Available_Slots__c.field-meta.xml
<CustomField>
    <fullName>Available_Slots__c</fullName>
    <description>This field will store the available slots of the room for that perticular date</description>
    <formula>Hotel_Product__r.Total_Quantity__c  -  Booked_Slots__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Slots</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booked_Date__c/fields/Booked_Slots__c.field-meta.xml
<CustomField>
    <fullName>Booked_Slots__c</fullName>
    <description>This Field Store the value of the Booked Slots. And Value of this field is Updated on the basis of the Record Creation of the Booked Dates.</description>
    <label>Booked Slots</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booked_Date__c/fields/Hotel_Product__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Booked Dates</relationshipLabel>
    <relationshipName>Booked_Dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <description>Hotel object is the custom object used to store the information about each hotel including different custom fields about that particular hotel.</description>
    <label>Hotel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>This Field will show the city of the Hotel</description>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Overall_Rating__c.field-meta.xml
<CustomField>
    <fullName>Overall_Rating__c</fullName>
    <description>This field stores the overall Average rating of a particular hotel</description>
    <formula>IF( Total_Reviews__c &lt;&gt; 0,( Avg_Cleanliness_And_Hygiene__c + Avg_Food_Quality__c + Avg_Value_For_Money__c + Avg_Hospitality__c ) / 4 , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Overall Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Total_Reviews__c.field-meta.xml
<CustomField>
    <fullName>Total_Reviews__c</fullName>
    <description>This Field Indicates total Number of reviews.</description>
    <label>Total Reviews</label>
    <summaryForeignKey>Review__c.Hotel__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Unique_Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Hotel_Name__c</fullName>
    <description>Stores the name of the hotel in kebab case format to uniquely distinguish them</description>
    <label>Unique Hotel Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hotel is the lookup to Hotel Object, which describes the hotel product is related to which Hotel.</description>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Hotel Products</relationshipLabel>
    <relationshipName>Hotel_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Hotel_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Product_Type__c</fullName>
    <description>Hotel Product Type is the custom field of type Picklist that is used to store the type of the Hotel Product. i.e. : Room, Dining, Swimming pool, Banquet hall, Conference room.</description>
    <label>Hotel Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Room</fullName>
            </value>
            <value>
                <fullName>Dining</fullName>
            </value>
            <value>
                <fullName>Swimming Pool</fullName>
            </value>
            <value>
                <fullName>Banquet Hall</fullName>
            </value>
            <value>
                <fullName>Conference Room</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Max_No_Of_Guest__c.field-meta.xml
<CustomField>
    <fullName>Max_No_Of_Guest__c</fullName>
    <description>Displays the max number of guests this room can accommodate</description>
    <label>Max No Of Guest</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Unit_Price__c</fullName>
    <description>Product Unit Price is the custom field that is used to store the Unit price of that perticular hotel product..</description>
    <label>Product Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Room_Area__c.field-meta.xml
<CustomField>
    <fullName>Room_Area__c</fullName>
    <description>Displays the sq m of the room.</description>
    <label>Room Area</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Room_Type__c.field-meta.xml
<CustomField>
    <fullName>Room_Type__c</fullName>
    <label>Room Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Hotel_Product_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Deluxe</fullName>
            </value>
            <value>
                <fullName>Semi-Deluxe</fullName>
            </value>
            <value>
                <fullName>Suite</fullName>
            </value>
            <value>
                <fullName>King Size</fullName>
            </value>
            <value>
                <fullName>Queen Size</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Total_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity__c</fullName>
    <label>Total Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RESBanquetController.cls
public without sharing class RESBanquetController {
    /*
    *********************************************************
    @Method Name    : getAllBanquetsAndConferenceDetails
    @author         : Milin Kapatel
    @description    : method to is used for fetching all banquets and conference details
    @param          : Date startDate, Date endDate
    @return         : List<Product2>
	@date			: April 25, 2025
	@JIRA			: 
    ********************************************************
	*/

    @AuraEnabled
    public static List<Product2> getAllBanquetsAndConferenceDetails(Date startDate, Date endDate) {
        try{

            List<Product2> banqAndConfDetails = [SELECT Id, Name, ProductCode, Hotel__c, Hotel__r.Overall_Rating__c, Hotel__r.Unique_Hotel_Name__c, Hotel__r.Name, Hotel__r.City__c, Hotel__r.Total_Reviews__c, Room_Type__c, Hotel_Product_Type__c, Product_Unit_Price__c, Image_URL__c, Room_Area__c, Total_Quantity__c, Max_No_Of_Guest__c, Description , (SELECT Id, Start_Date__c, End_Date__c, Booked_Slots__c, Available_Slots__c FROM Booked_Dates__r WHERE Start_Date__c >=:startDate AND End_Date__c <=:endDate) FROM Product2 WHERE Hotel_Product_Type__c = 'Banquet Hall' OR Hotel_Product_Type__c = 'Conference Room'];
            
            return banqAndConfDetails;
        }
        catch(Exception e){
            System.debug('Error in getAllBanquetsAndConferenceDetails: ' + e.getMessage());
            throw new AuraHandledException('Error fetching banquet and conference details ' + e.getMessage());
        }
    }
}