force-app/main/default/objects/Offer_Or_Quote__c/Offer_Or_Quote__c.object-meta.xml
<CustomObject>
    <label>Offer Or Quote</label>
    <nameField>
        <displayFormat>OQ-{000}</displayFormat>
        <label>Offers Or Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers Or Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer_Or_Quote__c/fields/Offer_Img_Url__c.field-meta.xml
<CustomField>
    <fullName>Offer_Img_Url__c</fullName>
    <label>Offer Img Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Offer_Or_Quote__c/fields/Quote_Description__c.field-meta.xml
<CustomField>
    <fullName>Quote_Description__c</fullName>
    <label>Quote Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Offer_Or_Quote__c/fields/Quote_Person_Img_Url__c.field-meta.xml
<CustomField>
    <fullName>Quote_Person_Img_Url__c</fullName>
    <label>Quote Person Img Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Offer_Or_Quote__c/fields/Quote_Person_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_Person_Name__c</fullName>
    <label>Quote Person Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offer_Or_Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offer_Or_Quote__c/recordTypes/Offer.recordType-meta.xml
<RecordType>
    <fullName>Offer</fullName>
    <active>true</active>
    <label>Offer</label>
</RecordType>

force-app/main/default/objects/Offer_Or_Quote__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

force-app/main/default/classes/RESHomePageCarouselController.cls
public without sharing class RESHomePageCarouselController {
    @AuraEnabled(cacheable = false)
    public static List<Offer_Or_Quote__c> getOfferItems(){
        try {
            List<Offer_Or_Quote__c> carouselItems = new List<SObject>();
            carouselItems.addAll([SELECT Id, Type__c, Offer_Img_Url__c FROM Offer_Or_Quote__c WHERE Type__c = 'Offer' LIMIT 6]);
            return carouselItems;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled(cacheable = false)
    public static List<Offer_Or_Quote__c> getQuoteItems(){
        try {
            List<Offer_Or_Quote__c> carouselItems = new List<SObject>();
            carouselItems.addAll([SELECT Id, Type__c,  Quote_Person_Name__c, Quote_Person_Img_Url__c, Quote_Description__c FROM Offer_Or_Quote__c WHERE Type__c = 'Quote' LIMIT 4]);
            return carouselItems;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}